spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: appuser
    password: apppassword
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

  # Optional: disable Docker Compose startup (if you're managing containers manually)
  docker:
    compose:
      enabled: true
      lifecycle-management: start_only
      readiness:
        timeout: 5m